### ISSUE TITLE
add selection in multi world

### ISSUE THREAD

**Issue by charlyg31** [BentoBoxWorld/Biomes#95]
### Is your feature request related to a problem?

Hello, i want is possible to add multi world for applied biome.

actually is possible to set:
overworld
nether
end

i want to add multi-selection

overworld
nether
end
overworld-nether
overworld-end
nether-end
overworld-nether-end
.
Actually is possible, but i need to create two same biome one for overworld and one for nether or three for end too.

### Describe the solution you'd like.

just multi selection.

### Describe alternatives you've considered.

i d'ont have alternative.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
I am against this change because of a simple fact: biomes that are not meant for dimension (like plains in the nether), will completely break that dimension.

In Minecraft, a lot of mechanics are linked to the biome: placing water in the nether biomes is not possible regardless of which dimension it is, and the same in another way, placing water in plains is possible regardless of dimension.

Entity spawning also is linked to the biome, not dimension. So putting nether waste biome in the overworld will start to spawn zombified piglins.
